FROM nginx:1.15.0-alpine

# Remove o arquivo padrão de configuração do nginx e substitui pelo arquivo nginx.conf existente nesta pasta
RUN rm etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Cria o diretório se não existir, e cria um arquivo index.php
RUN mkdir /var/www/html -p && touch /var/www/html/index.php